/**
 * Generated by `scripts/landing-fixture.mjs`. Do not edit by hand.
 *
 * **What the page draws, and all it ships.** Each window is the last `shown`
 * readings and the trend from one vertex before them; the readings the trend
 * was warmed up on are in `fixture.source.generated.ts`, which the page never
 * imports.
 *
 * `landing-fixture.test.ts` recomputes §4.1 over the whole series and fails on
 * any vertex here that differs, so an edit to this file is caught rather than
 * believed.
 *
 * Fixtures, never an account: the landing page is public and D9 says this data
 * belongs to whoever logged it.
 */

export const HERO = {
  /** How many readings this window holds, which is what the page draws. */
  shown: 30,
  readings: [
    { localDate: "2026-07-19", weightKg: 92.4 },
    { localDate: "2026-07-21", weightKg: 91.9 },
    { localDate: "2026-07-23", weightKg: 91.9 },
    { localDate: "2026-07-25", weightKg: 92.4 },
    { localDate: "2026-07-27", weightKg: 92.1 },
    { localDate: "2026-07-29", weightKg: 92.2 },
    { localDate: "2026-07-31", weightKg: 91.7 },
    { localDate: "2026-08-02", weightKg: 92.3 },
    { localDate: "2026-08-04", weightKg: 91.6 },
    { localDate: "2026-08-06", weightKg: 91.5 },
    { localDate: "2026-08-08", weightKg: 91.3 },
    { localDate: "2026-08-10", weightKg: 91.3 },
    { localDate: "2026-08-12", weightKg: 91.2 },
    { localDate: "2026-08-14", weightKg: 91.4 },
    { localDate: "2026-08-16", weightKg: 91.2 },
    { localDate: "2026-08-18", weightKg: 91.3 },
    { localDate: "2026-08-20", weightKg: 91.4 },
    { localDate: "2026-08-22", weightKg: 91.4 },
    { localDate: "2026-08-24", weightKg: 91 },
    { localDate: "2026-08-26", weightKg: 91.1 },
    { localDate: "2026-08-28", weightKg: 91.1 },
    { localDate: "2026-08-30", weightKg: 91.2 },
    { localDate: "2026-09-01", weightKg: 91.1 },
    { localDate: "2026-09-03", weightKg: 90.7 },
    { localDate: "2026-09-05", weightKg: 90.9 },
    { localDate: "2026-09-07", weightKg: 91.1 },
    { localDate: "2026-09-09", weightKg: 91.2 },
    { localDate: "2026-09-11", weightKg: 90.8 },
    { localDate: "2026-09-13", weightKg: 90.4 },
    { localDate: "2026-09-15", weightKg: 90.1 },
  ],
  trend: [
    { localDate: "2026-07-17", trendKg: 92.77 },
    { localDate: "2026-07-19", trendKg: 92.699 },
    { localDate: "2026-07-21", trendKg: 92.547 },
    { localDate: "2026-07-23", trendKg: 92.424 },
    { localDate: "2026-07-25", trendKg: 92.42 },
    { localDate: "2026-07-27", trendKg: 92.359 },
    { localDate: "2026-07-29", trendKg: 92.329 },
    { localDate: "2026-07-31", trendKg: 92.209 },
    { localDate: "2026-08-02", trendKg: 92.227 },
    { localDate: "2026-08-04", trendKg: 92.108 },
    { localDate: "2026-08-06", trendKg: 91.992 },
    { localDate: "2026-08-08", trendKg: 91.861 },
    { localDate: "2026-08-10", trendKg: 91.754 },
    { localDate: "2026-08-12", trendKg: 91.649 },
    { localDate: "2026-08-14", trendKg: 91.602 },
    { localDate: "2026-08-16", trendKg: 91.525 },
    { localDate: "2026-08-18", trendKg: 91.482 },
    { localDate: "2026-08-20", trendKg: 91.467 },
    { localDate: "2026-08-22", trendKg: 91.454 },
    { localDate: "2026-08-24", trendKg: 91.368 },
    { localDate: "2026-08-26", trendKg: 91.317 },
    { localDate: "2026-08-28", trendKg: 91.276 },
    { localDate: "2026-08-30", trendKg: 91.261 },
    { localDate: "2026-09-01", trendKg: 91.231 },
    { localDate: "2026-09-03", trendKg: 91.13 },
    { localDate: "2026-09-05", trendKg: 91.086 },
    { localDate: "2026-09-07", trendKg: 91.089 },
    { localDate: "2026-09-09", trendKg: 91.11 },
    { localDate: "2026-09-11", trendKg: 91.051 },
    { localDate: "2026-09-13", trendKg: 90.927 },
    { localDate: "2026-09-15", trendKg: 90.77 },
  ],
} as const;

export const FORTNIGHT = {
  /** How many readings this window holds, which is what the page draws. */
  shown: 14,
  readings: [
    { localDate: "2026-08-24", weightKg: 84.6 },
    { localDate: "2026-08-25", weightKg: 84.4 },
    { localDate: "2026-08-26", weightKg: 84.6 },
    { localDate: "2026-08-27", weightKg: 84.4 },
    { localDate: "2026-08-28", weightKg: 84.4 },
    { localDate: "2026-08-29", weightKg: 84.3 },
    { localDate: "2026-08-30", weightKg: 84.2 },
    { localDate: "2026-08-31", weightKg: 84.4 },
    { localDate: "2026-09-01", weightKg: 84.8 },
    { localDate: "2026-09-02", weightKg: 84.6 },
    { localDate: "2026-09-03", weightKg: 84 },
    { localDate: "2026-09-04", weightKg: 84.3 },
    { localDate: "2026-09-05", weightKg: 84.4 },
    { localDate: "2026-09-06", weightKg: 84.2 },
  ],
  trend: [
    { localDate: "2026-08-23", trendKg: 84.866 },
    { localDate: "2026-08-24", trendKg: 84.84 },
    { localDate: "2026-08-25", trendKg: 84.796 },
    { localDate: "2026-08-26", trendKg: 84.776 },
    { localDate: "2026-08-27", trendKg: 84.739 },
    { localDate: "2026-08-28", trendKg: 84.705 },
    { localDate: "2026-08-29", trendKg: 84.664 },
    { localDate: "2026-08-30", trendKg: 84.618 },
    { localDate: "2026-08-31", trendKg: 84.596 },
    { localDate: "2026-09-01", trendKg: 84.616 },
    { localDate: "2026-09-02", trendKg: 84.615 },
    { localDate: "2026-09-03", trendKg: 84.553 },
    { localDate: "2026-09-04", trendKg: 84.528 },
    { localDate: "2026-09-05", trendKg: 84.515 },
    { localDate: "2026-09-06", trendKg: 84.484 },
  ],
} as const;
