import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

/**
 * The landing page's checkable claims (D97, rebuilt in D173).
 *
 * The page argues that this app does not round its own measurements, so the
 * claims it makes about itself are pinned to the places those measurements are
 * recorded. A page that goes on saying something that was true last month is
 * the exact failure it is arguing against.
 *
 * The figure strip this file was written for is gone with the rebuild. What
 * replaced it is claims inside prose, which are harder to spot and no less
 * checkable, so the pinning moved with them rather than being dropped.
 */

const ROOT = path.resolve(import.meta.dirname, "../../..");
const LANDING = readFileSync(path.join(ROOT, "apps/web/src/landing/Landing.tsx"), "utf8");
const MEASURED = readFileSync(path.join(ROOT, "docs/measurements.md"), "utf8");

/** The row of the fast-path table the page quotes. */
function measuredRepeatTaps(): number {
  const row = MEASURED.split("\n").find((line) => line.includes("repeat food, cold open to logged"));
  expect(row, "docs/measurements.md no longer has a repeat-food row in its fast-path table").toBeTruthy();

  // The last figure on the row is the current one; earlier columns are history.
  const taps = [...row!.matchAll(/(\d+)\s+taps?/g)].at(-1);
  expect(taps, `no tap count in: ${row}`).toBeTruthy();
  return Number(taps![1]);
}

/**
 * Swedish spells a small number in a sentence, and the table counts it.
 *
 * The strip could hold a digit beside a unit; a sentence cannot without reading
 * like a specification. So the test crosses the gap rather than the copy: it
 * converts the measured figure to the word the page would use, and fails naming
 * both if the measurement moves.
 */
const WORDS = ["noll", "ett", "två", "tre", "fyra", "fem"];

describe("what the landing page claims about itself", () => {
  it("says the tap count that was actually measured", () => {
    const taps = measuredRepeatTaps();
    const word = WORDS[taps];
    expect(word, `no Swedish word for ${taps} taps`).toBeTruthy();

    expect(
      LANDING,
      `docs/measurements.md now says ${taps} taps, so the page should say "${word} tryck"`,
    ).toContain(`${word} tryck`);
  });

  /**
   * Three screens, and each is a real capture.
   *
   * A section whose screenshot went missing lays out correctly with a broken
   * image, which is exactly why this is worth pinning. They are regenerated by
   * `scripts/landing-shots.mjs` from the seeded demo account, so a stale one is
   * a run that did not happen rather than a file somebody forgot.
   */
  it("shows three screenshots, each of which exists", () => {
    const sources = [...LANDING.matchAll(/src:\s*"(\/screens\/[^"]+)"/g)].map((m) => m[1]!);
    expect(new Set(sources).size).toBe(3);

    for (const source of sources) {
      const file = path.join(ROOT, "apps/web/public", source);
      expect(() => readFileSync(file), `${source} is referenced but not in public/`).not.toThrow();
    }
  });

  /**
   * The claim this file exists for (D111).
   *
   * A card once said "100 % av din data ligger på din egen server", which is
   * true for a reader who self-hosts and false for a reader on somebody else's
   * instance, and the page cannot tell them apart. The rebuilt page says the
   * conditional form instead, and this holds it there: the unconditional
   * sentence must not come back.
   */
  it("never tells an unknown reader the data is on their own server", () => {
    const prose = LANDING
      .replace(/\{\/\*[\s\S]*?\*\/\}/g, "")
      .replace(/\/\*[\s\S]*?\*\//g, "")
      .replace(/^\s*\/\/.*$/gm, "");

    /*
      The claim, not the words. "kör den på en egen server" is an offer and is
      true for anybody; "din data ligger på din egen server" is a statement
      about this reader's data and is false for half of them.
    */
    expect(prose).not.toMatch(/ligger på din egen server/);
    expect(prose).not.toMatch(/100 % av din data/);
    // And the conditional version is present, so this is not passing by the
    // sentence having been dropped altogether.
    expect(prose).toMatch(/Kör du den själv är det din/);
  });

  /**
   * The page draws numbers, and none of them is anybody's.
   *
   * Every figure on the rebuilt page comes from `seeded.ts`, which generates a
   * body from a maintenance figure and 7 700 kcal per kilo. A landing page that
   * illustrated itself with a real account would be publishing the one thing
   * D9 says belongs to the person who logged it.
   */
  it("draws its graphs from the fixture rather than from an account", () => {
    expect(LANDING).toMatch(/from "\.\/seeded\.js"/);
    expect(LANDING).not.toMatch(/fetch\(|useQuery|\/api\//);
  });
});
