#!/usr/bin/env node
/**
 * The landing page's two graphs, computed rather than drawn (D177).
 *
 *   pnpm --filter api landing-fixture
 *
 * Writes `apps/web/src/landing/fixture.generated.ts`: two series of dated
 * readings, and the trend through each **from `packages/shared`'s own EMA**,
 * which is the function the app's chart uses.
 *
 * ## Why this is generated rather than imported
 *
 * The page could call `computeTrend` in the browser. It would be honest and it
 * would put §4.1 and its dependencies into a bundle that exists to show a
 * stranger one picture. Generating the numbers keeps the page at a list of
 * coordinates, and `landing-fixture.test.ts` runs the same calc over the same
 * readings and fails if a single vertex differs. The guarantee is the test, not
 * the comment.
 *
 * ## Why it is not a drawn curve
 *
 * It was one: a cubic with four control points, chosen because it looked like a
 * trend. A landing page whose whole argument is "this app draws the trend
 * rather than the noise" cannot illustrate it with a shape somebody drew by
 * hand, and nothing would have caught it if the app's smoothing changed.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
/*
  The source, by path. `scripts/` is not a workspace package and has no
  dependency on `shared`; tsx loads the TypeScript directly, and the point of
  this script is to use the app's own §4.1 rather than a copy of it.
*/
import { computeTrend } from "../packages/shared/src/index.ts";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "apps/web/src/landing/fixture.generated.ts");

/** The same generator the page used before, so the picture does not change. */
function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const addDays = (date, days) => {
  const at = new Date(`${date}T12:00:00Z`);
  at.setUTCDate(at.getUTCDate() + days);
  return at.toISOString().slice(0, 10);
};

/**
 * The hero: two months of a body that is losing weight, weighed every other day.
 *
 * Thirty readings across sixty days, which is the cadence the smoothing is
 * built for: §4.1's alpha is **per day**, so a gap compounds it, and weighing
 * every third day turns a ten-day constant into an effective 0,27 that chases
 * the noise instead of cutting through it. At every other day it is 0,19 and
 * the line reads as a trend, which is the thing the page is about.
 *
 * The scatter is the daily swing a real scale shows, about a kilo either way,
 * and the underlying loss is a little under a kilo a month. Both are ordinary.
 */
function heroReadings() {
  const random = mulberry32(20260917);
  const start = "2026-07-19";
  const readings = [];

  for (let day = 0; day < 60; day += 2) {
    const underlying = 92.4 - day * 0.031;
    const swing = (random() - 0.5) * 2.1;
    readings.push({
      localDate: addDays(start, day),
      weightKg: Number((underlying + swing).toFixed(1)),
    });
  }

  return readings;
}

/**
 * The fortnight: fourteen consecutive mornings.
 *
 * The scatter is tightened to about 0,8 kg from the trend, which is what a day
 * to day swing actually looks like. The first version scattered by 1,7 and drew
 * a cloud nobody would recognise from their own bathroom scale.
 */
function fortnightReadings() {
  const random = mulberry32(140314);
  const start = "2026-08-24";
  const readings = [];

  for (let day = 0; day < 14; day += 1) {
    const underlying = 84.6 - day * 0.031;
    const swing = (random() - 0.5) * 0.8;
    readings.push({
      localDate: addDays(start, day),
      weightKg: Number((underlying + swing).toFixed(1)),
    });
  }

  return readings;
}

/** `computeTrend` returns a point per day; the page draws the days with a reading. */
function trendFor(readings) {
  const byDate = new Map(computeTrend(readings).map((point) => [point.localDate, point.trend]));
  return readings.map((reading) => ({
    localDate: reading.localDate,
    trendKg: Number(byDate.get(reading.localDate).toFixed(3)),
  }));
}

const hero = heroReadings();
const fortnight = fortnightReadings();

const series = (name, readings, trend) =>
  `export const ${name} = {
  readings: [
${readings.map((r) => `    { localDate: "${r.localDate}", weightKg: ${r.weightKg} },`).join("\n")}
  ],
  trend: [
${trend.map((t) => `    { localDate: "${t.localDate}", trendKg: ${t.trendKg} },`).join("\n")}
  ],
} as const;`;

writeFileSync(
  OUT,
  `/**
 * Generated by \`scripts/landing-fixture.mjs\`. Do not edit by hand.
 *
 * Two series of dated readings and the trend through each, from
 * \`packages/shared\`'s EMA (§4.1). \`landing-fixture.test.ts\` recomputes both
 * from the readings below and fails on any difference, so an edit here is
 * caught rather than believed.
 *
 * Fixtures, never an account: the landing page is public and D9 says this data
 * belongs to whoever logged it.
 */

${series("HERO", hero, trendFor(hero))}

${series("FORTNIGHT", fortnight, trendFor(fortnight))}
`,
  "utf8",
);

process.stdout.write(
  `wrote ${path.relative(ROOT, OUT)}: ${hero.length} hero readings, ${fortnight.length} daily\n`,
);
